name: CI_docker_build_push_acr-for-dotnet
on:
  push:
    branches: [ "dckrazct" ]
  pull_request:
    branches: [ "dckrazct" ]

 # this will allow to run workflow manually from the action tab.
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
         name: Checkout
         uses: actions/checkout@v2
      - 
         name: Docker Login
         uses: azure/docker-login@v1
         with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

      -  
         name: Build the frontend image and push it to ACR
         uses: docker/build-push-action@v2
         with:
           push: true
           file: app/Dockerfile
           tags: demoregstr.azurecr.io/samplewebapp:latest, demoregstr.azurecr.io/samplewebapp:${{github.run_number}}
   
